name: CI - Python (pytest + Selenium)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: chrome --version

      - name: Run pytest
        env:
          # 可選：若你有私有測站，改用 Secrets 傳入
          # ROUTER_URL: ${{ secrets.ROUTER_URL }}
        run: pytest -q

      - name: Upload artifacts (logs/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            screenshots/**
            logs/**
            *.log
          if-no-files-found: ignore
